version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    tty: true
  mariadb:
    image: mariadb:11.0.3
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
